# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApOU20QQxfcVfyq5VgsyPUPdJ664qWoT
"""

import os

os.makedirs("src", exist_ok=True)
os.makedirs("data", exist_ok=True)
os.makedirs("models", exist_ok=True)

with open("src/preprocess.py", "w") as f:
    f.write("""
import pandas as pd

def load_and_preprocess(path):
    df = pd.read_csv(path)
    df.fillna(0, inplace=True)
    df['build_duration'] = pd.to_numeric(df['build_duration'], errors='coerce')
    df['label'] = df['status'].apply(lambda x: 1 if x == 'Failed' else 0)
    features = df[['build_duration', 'num_commits', 'num_changed_files']]
    labels = df['label']
    return features, labels
""")

with open("src/train_model.py", "w") as f:
    f.write("""
import os
import sys
sys.path.append(os.path.abspath("."))  # Add root path

from src.preprocess import load_and_preprocess
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib

X, y = load_and_preprocess('data/sample_build_data.csv')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("✅ Model Accuracy:", accuracy)

os.makedirs("models", exist_ok=True)
joblib.dump(model, "models/model.pkl")
print("✅ Model saved at models/model.pkl")
""")

import os
import joblib
import pandas as pd

model_path = "models/model.pkl"
assert os.path.exists(model_path), "❌ Model not found. Run train_model.py first."

model = joblib.load(model_path)

def predict(build_duration, num_commits, num_changed_files):
    input_df = pd.DataFrame([[build_duration, num_commits, num_changed_files]],
                            columns=["build_duration", "num_commits", "num_changed_files"])
    result = model.predict(input_df)
    return "Build likely to fail" if result[0] == 1 else "Build likely to succeed"

# ✅ Take input from user
build_duration = float(input("Enter build duration (in seconds): "))
num_commits = int(input("Enter number of commits: "))
num_changed_files = int(input("Enter number of changed files: "))

result = predict(build_duration, num_commits, num_changed_files)
print("🔮 Prediction:", result)

import pandas as pd
import random

data = []
for i in range(100):
    build_duration = random.randint(100, 1000)
    num_commits = random.randint(1, 15)
    num_changed_files = random.randint(1, 50)
    status = "Failed" if (build_duration > 700 and num_changed_files > 25) else "Passed"
    data.append({
        "build_id": i + 1,
        "build_duration": build_duration,
        "num_commits": num_commits,
        "num_changed_files": num_changed_files,
        "status": status
    })

df = pd.DataFrame(data)
df.to_csv("data/sample_build_data.csv", index=False)

!python3 src/train_model.py
!python3 src/predict.py

!python3 src/train_model.py

!python3 src/predict.py

# Import the predict function from the src.predict module
from src.predict import predict

print("🧠", predict(850, 6, 40))
print(predict(300, 2, 5))  # Likely to succeed

from src.predict import predict

# Example: Manually input test build features
result = predict(700, 3, 15)
print("🔮 Prediction:", result)